# Site settings
title: Mehdi Luthon personnal website
# title: Anon dev personnal website
description: my portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mehdi Luthon
# username: Anon dev
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Full-Stack Developer
email: lockee14@msn.com
angel_list: https://angel.co/mehdi-luthon
github_username: https://github.com/lockee14
linkedin: https://www.linkedin.com/in/mehdi-luthon/
excerpt_separator: <!--more-->
# Google-analytics
google-analytics:
  id: "UA-145148279-1"

exclude: ['package.json', 'node_modules']
sass:
    sass_dir: src/_sass
    style: compressed